apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
        image: freddygv/hello-http:v0.2.2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
