apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http
  labels:
    app: hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "hello"
    spec:
      containers:
      - name: hello-http
        image: freddygv/hello-http:v0.2.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
