apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-client
  labels:
    app: hello-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-client
  template:
    metadata:
      labels:
        app: hello-client
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "client"
        "consul.hashicorp.com/connect-service-upstreams": "hello:8080"
    spec:
      containers:
      - name: hello-client
        image: freddygv/hello-client:v0.2.0
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
