global:
  enabled: true
  domain: consul
  image: "consul:1.5.0"
  imageK8S: "hashicorp/consul-k8s:0.9.0"
  datacenter: dc1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

# Configures Consul clients to run on every node
client:
  enabled: true

# Configures consul-dns service that routes to all agents
dns:
  enabled: true

ui:
  enabled: true
  service:
    type: NodePort