global:
  enabled: true
  datacenter: dc1
  image: "freddygv/consul-dev:tproxy2-v0.06"

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1

# Configures Consul clients to run on every node
client:
  enabled: true
  grpc: true # Needed for Connect

connectInject:
  enabled: true
  envoyExtraArgs: "-l trace"

# Configures consul-dns service that routes to all agents
dns:
  enabled: true

ui:
  enabled: true
  service:
    type: LoadBalancer